title: Pol Garcia Recasens
url: "https://pgarec.github.io"
baseurl: ""

markdown: kramdown

tracking_id: #

footer: yes
footer_url: "https://github.com/pgarec"

sass:
   style: compressed
   sass_dir: _sass

nav:
- name: "About"
  link: "/"
- name: "Teaching"
  link: "/pages/teaching"
- name: "Talks"
  link: "/pages/talks"
- name: "Publications"
  link: "/pages/publications"
- name: "Work"
  link: "/pages/work"
- name: "Contact"
  link: "/pages/contact"


